name: CI-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           python36-windows-2019,
           python38-ubuntu2004,
           python37-macOS110
        ]
        include:
        - name: python36-windows-2019
          python-version: 3.6
          os: windows-2019

        - name: python38-ubuntu2004
          python-version: 3.8
          os: ubuntu-20.04

        - name: python37-macOs11.0
          python-version: 3.6
          os: macOs11.0

    steps:
    - name: Checkout simple_functions
      uses: actions/checkout@v1

    - name: Install dependencies Ubuntu
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get install python3-setuptools -y
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Install dependencies windows
      if: matrix.os == 'windows-2019'
      run: |
        install python3-setuptools -y
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
    
    - name: Install dependencies Mac
      if: matrix.os == 'macos-11.0'
      run: |
        wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Test with pytest
      if: matrix.os != 'windows-2019'
      run: |
        python3 -m pytest --doctest-modules tests/test_algos.py
        python3 tests/test_docstrings.py

